### PR TITLE
fix: unify access_token/accessToken and refresh_token/refreshToken credential keys

### LINKED ISSUE #985: Unify access_token/accessToken & refresh_token& refreshToken
**Description**
The OCI resource repository ([resource_repository.go#L272-L287](https://github.com/open-component-model/open-component-model/blob/main/bindings/go/oci/repository/resource/resource_repository.go#L272)) uses different key names than the component version repository path:

// oci/repository/resource/resource_repository.go — uses snake_case
credentials["refresh_token"]  // ← snake_case
credentials["access_token"]   // ← snake_case

// oci/credentials/docker_config.go — uses camelCase
CredentialKeyRefreshToken = "refreshToken"  // ← camelCase
CredentialKeyAccessToken  = "accessToken"   // ← camelCase
Docker config can produce tokens. The Docker config.json supports identitytoken and registrytoken fields, and credential helpers (ECR, GCR, Azure ACR, osxkeychain) can return them. ORAS maps these to auth.Credential.RefreshToken / AccessToken, and ResolveV1DockerConfigCredentials() writes them as accessToken/refreshToken (camelCase) into the map.

The two OCI consumer paths diverge:

Component version repository (provider.go:145) uses CredentialFunc() from docker_config.go → reads accessToken/refreshToken (camelCase) — matches Docker config output
Resource repository (resource_repository.go:253) uses its own clientCredentials() → reads access_token/refresh_token (snake_case) — does NOT match Docker config output

#### Open topics
- [ ] should we support both ways of providing keys in this case for compatibility

**Done Criteria**
- [ ] Unify keys 
- [ ] Keep or drop both key versions
- [ ] Code has been reviewed by other team members
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Internal technical Documentation created/updated (if applicable)
- [ ] Successful demonstration in Review

### PR DESCRIPTION
**Pull request by matthiasbruns**
#### What this PR does / why we need it

The OCI resource repository (`resource_repository.go`) used snake_case credential keys (`access_token`, `refresh_token`) while the rest of the codebase—including `docker_config.go` and the component version repository path—uses camelCase (`accessToken`, `refreshToken`). This mismatch caused silent authentication failures when tokens from Docker config (which produces camelCase keys) were used for OCI resource downloads.

This PR:
- Updates `clientCredentials()` in `resource_repository.go` to use the canonical `CredentialKey*` constants (camelCase) as the primary keys
- Updates `CredentialFunc()` in `docker_config.go` to also accept legacy snake_case keys
- Adds `LegacyCredentialKeyAccessToken` and `LegacyCredentialKeyRefreshToken` constants (marked deprecated) so legacy keys are not scattered as string literals
- Falls back to the legacy snake_case keys for backward compatibility, with camelCase taking precedence when both are present

#### Which issue(s) this PR fixes

Fixes open-component-model/ocm-project#985

##### How to test the changes

1. Run unit tests: `go test ./bindings/go/oci/credentials/... ./bindings/go/oci/repository/resource/...`
2. Verify that credentials with camelCase keys (`accessToken`, `refreshToken`) are correctly resolved in both the component version and resource repository paths
3. Verify that credentials with legacy snake_case keys (`access_token`, `refresh_token`) still work for backward compatibility

##### Verification

- [x] I have added/updated tests for my changes (see [Test Requirements](../CONTRIBUTING.md#test-requirements))
- [x] Tests pass locally (`task test` and `task test/integration` if applicable)
- [ ] If touching multiple modules, `go work` is enabled (see `go.work`)
- [x] My changes do not decrease test coverage
- [ ] I have tested the changes locally by running `ocm`

### CODE REVIEW

File: bindings/go/oci/credentials/docker_config.go [hunk 1]
```diff
@@ -28,6 +28,13 @@ const (
 	CredentialKeyAccessToken = "accessToken"
 	// CredentialKeyRefreshToken is the key for storing refresh token credentials
 	CredentialKeyRefreshToken = "refreshToken"
+
+	// LegacyCredentialKeyAccessToken is the legacy snake_case key for access tokens.
+	// Deprecated: Use CredentialKeyAccessToken instead.
+	LegacyCredentialKeyAccessToken = "access_token"
+	// LegacyCredentialKeyRefreshToken is the legacy snake_case key for refresh tokens.
+	// Deprecated: Use CredentialKeyRefreshToken instead.
+	LegacyCredentialKeyRefreshToken = "refresh_token"
```
[the remark this answers is not in the document]
Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config.go:39]: done

File: bindings/go/oci/credentials/docker_config_test.go [hunk 2]
```diff
@@ -27,8 +28,8 @@ func TestCredentialFunc(t *testing.T) {
 				runtime.IdentityAttributePort:     "443",
 			},
 			credentials: map[string]string{
-				CredentialKeyUsername: "testuser",
-				CredentialKeyPassword: "testpass",
+				"username": "testuser",
+				"password": "testpass",
```
Comment (piotrjanik) [inline bindings/go/oci/credentials/docker_config_test.go:32]: Why strings?

File: bindings/go/oci/credentials/docker_config_test.go [hunk 3]
```diff
@@ -165,8 +267,8 @@ func TestResolveV1DockerConfigCredentials(t *testing.T) {
 				runtime.IdentityAttributeHostname: "registry.example.com",
 			},
 			wantCreds: map[string]string{
-				CredentialKeyUsername: "testuser",
-				CredentialKeyPassword: "testpass",
+				"username": "testuser",
+				"password": "testpass",
```
Comment (fabianburth) [inline bindings/go/oci/credentials/docker_config_test.go:271]: why?

File: bindings/go/oci/credentials/docker_config.go [hunk 4]
```diff
@@ -28,8 +28,41 @@ const (
...
+	// LegacyCredentialKeyRefreshToken is the legacy snake_case key for refresh tokens.
+	//
+	// Deprecated: Use CredentialKeyRefreshToken instead.
+	LegacyCredentialKeyRefreshToken = "refresh_token"
 )
 
+// CredentialFromMap converts a credential map to an auth.Credential.
+// It supports both canonical camelCase keys and legacy snake_case keys for token fields,
+// with camelCase taking precedence.
+func CredentialFromMap(credentials map[string]string) auth.Credential {
```
Comment (fabianburth) [inline bindings/go/oci/credentials/docker_config.go:45]: Should we have a deprecation issue to track this?

Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config.go:45]: Good question - We will probably touch this again when we migrate to oci typed credentials. I can add a ticket now to track this

File: bindings/go/oci/credentials/docker_config_test.go (hunk 3 above)
Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config_test.go:271]: the commit says "chore: test for accidental consts changes by hardcoding the strings in the tests"

File: bindings/go/oci/credentials/docker_config_test.go [hunk 5]
```diff
@@ -107,22 +140,91 @@ func TestCredentialFunc(t *testing.T) {
...
+				RefreshToken: "rtoken",
+			},
+		},
+		{
+			name: "camelCase takes precedence over snake_case",
+			credentials: map[string]string{
+				"accessToken":   "camel",
+				"access_token":  "snake",
+				"refreshToken":  "camel-refresh",
+				"refresh_token": "snake-refresh",
```
Comment (piotrjanik) [inline bindings/go/oci/credentials/docker_config_test.go:211]: Isn't this a bit confusing? It means that user can mix camel with snake. Even could provide access_token and refreshToken.

File: bindings/go/oci/credentials/docker_config.go [hunk 6]
```diff
@@ -28,8 +28,41 @@ const (
...
 	// CredentialKeyRefreshToken is the key for storing refresh token credentials
 	CredentialKeyRefreshToken = "refreshToken"
+
+	// LegacyCredentialKeyAccessToken is the legacy snake_case key for access tokens.
+	//
+	// Deprecated: Use CredentialKeyAccessToken instead.
+	LegacyCredentialKeyAccessToken = "access_token"
+	// LegacyCredentialKeyRefreshToken is the legacy snake_case key for refresh tokens.
+	//
+	// Deprecated: Use CredentialKeyRefreshToken instead.
```
Comment (matthiasbruns) [inline bindings/go/oci/credentials/docker_config.go]:
```suggestion
	// Deprecated: Use CredentialKeyRefreshToken instead. The removal of this key is tracked here: https://github.com/open-component-model/ocm-project/issues/1037
```

File: bindings/go/oci/credentials/docker_config.go [hunk 7]
```diff
@@ -28,8 +28,41 @@ const (
 	CredentialKeyAccessToken = "accessToken"
 	// CredentialKeyRefreshToken is the key for storing refresh token credentials
 	CredentialKeyRefreshToken = "refreshToken"
+
+	// LegacyCredentialKeyAccessToken is the legacy snake_case key for access tokens.
+	//
+	// Deprecated: Use CredentialKeyAccessToken instead.
```
Comment (matthiasbruns) [inline bindings/go/oci/credentials/docker_config.go]:
```suggestion
	// Deprecated: Use CredentialKeyAccessToken instead. The removal of this key is tracked here: https://github.com/open-component-model/ocm-project/issues/1037
```

**Review by piotrjanik — COMMENTED** [review]
LGTM. Two nits.

File: bindings/go/oci/credentials/docker_config.go (hunk 4 above)
Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config.go:45]: https://github.com/open-component-model/ocm-project/issues/1037 done

File: bindings/go/oci/credentials/docker_config_test.go (hunk 5 above)
Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config_test.go:211]: this is only for compatibility, the two keys where conflicting - see the issue. We will 100% remove the fallback in the near future - we should only document the `camelCase` variant anyway

here is the issue for the removal
https://github.com/open-component-model/ocm-project/issues/1037

File: bindings/go/oci/credentials/docker_config_test.go (hunk 2 above)
Comment (matthiasbruns) [reply bindings/go/oci/credentials/docker_config_test.go:32]: https://github.com/open-component-model/open-component-model/pull/2383#discussion_r3136061759 thats why

**Review by morri-son — APPROVED** [review]

**Review by fabianburth — APPROVED** [review]
